### PR TITLE
Fixed bug #520: childrenCount() and children() not working on PostgreSQL

### LINKED ISSUE #520: childrenCount() and children() not working on PostgreSQL
(Similar to Issues #382 and #400)
## The Problem
childrenCount() returns 0 and children() returns empty array.
Inspection of the code reveals that the query constructed by childrenCount() selects only COUNT(*) but includes a default ORDER BY clause which fails because its columns are not in a GROUP BY clause. I am pretty sure the ORDER BY clause and the optional LIMIT and OFFSET clauses can be removed.
The queries in both childrenCount() and children() use a condition:
```
COALESCE(valid_until, '') = ''
```
where valid_until is a timestamp. In Postgres empty strings cannot be CAST to timestamps so this fails. 
I have patched my local install to
```
valid_until IS_NULL
```
which seems to work (on Postgres at least).
## The Conditions
Fresh install of 0.7.7 on Postgres 9.1 and Apache 2.2 on Windows XP

### PR DESCRIPTION
**Pull request by korbeljak**
Fixes #520 

Changes proposed in this pull request:

- use valid_until IS NULL instead of COALESCE(valid_until, '') == '', since the PostgreSQL takes '' as invalid timestamp.

@wolfcms/core-developers

### CODE REVIEW

**Comment by mvdkleijn** [comment]
Did you test this against SQLite and mySQL? I believe we don't have automated tests for this particular item.

**Comment by korbeljak** [comment]
I have only MySQL tested right now, I will give SQLite a shot and let you know about the outcome.

**Comment by korbeljak** [comment]
To be honest, I cannot even run the WolfCMS using SQLite 3.11.1/ PHP 7.0.4, since WolfCMS looks for wolf_setting table, which is missing.

**Comment by korbeljak** [comment]
Reported as #649 .

**Comment by korbeljak** [comment]
The change is working for SQLite as well, I have tried it right now.

**Pull request closed without merging**
