### PR TITLE
Update FileManagerController.php

### PR DESCRIPTION
**Pull request by svanlaere**
Fixed call to htmlContextCleaner

### CODE REVIEW

**Comment by mvdkleijn** [comment]
sorry about that, it was supposed to be in there... put out a 0.8.3.1 now

**Comment by svanlaere** [comment]
That doesn't mean I need to overwrite Wolf's index.php again?

**Comment by mvdkleijn** [comment]
no

**Comment by svanlaere** [comment]
That makes me happy, just upgraded multiple Wolf powered sites.

**Comment by svanlaere** [comment]
Still, this notification gets show on admin login:
Information! New Wolf version available (v. 0.8.3.1)!

Seems that CMS_VERSION needs to be incremented to prevent that from happening,
either that or setting CHECK_UPDATES to false but that is less ideal.

**Pull request merged**
